### ISSUE TITLE
Mothim doesnt have any forms.

### ISSUE THREAD

**Issue by LuziferSenpai** [PokeAPI/pokeapi#593]
Hey,

I just found out that, mothim doesnt have the forms of the base pokemon, so why are there 2 listed?

It would be nice if they get removed.

**Comment by Naramsim** [comment]
Those forms are present in Pokemon Go, not sure if they should be in this repository.

**Comment by LuziferSenpai** [comment]
They are not. I just looked it up and I dont find any entry to this. Only the female version has forms, not the male version.

**Comment by phalt** [comment]
> This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

Not sure if this helps make the decision (and I know things have changed since 2013) but the original scope of this service was just the main game series.

Is Meltan part of this API? That might have already made the decision for us.

**Comment by LuziferSenpai** [comment]
> > This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
> 
> Not sure if this helps make the decision (and I know things have changed since 2013) but the original scope of this service was just the main game series.
> 
> Is Meltan part of this API? That might have already made the decision for us.

Meltan is a pokemon from the main series since gen 8, its final evolution even has a gmax form ;)

**Comment by Naramsim** [comment]
I don't know. Maybe it's better to remove those. I need to check out how they got in, anyway.

**Comment by C-Garza** [comment]
They were added to the pokemon_forms.csv in this [commit at Veekun](https://github.com/veekun/pokedex/commit/45f43231e32d17f8997a823e838d27ad191b3915#diff-1a83d06db25989069895dc345a0a141b1fbc9843b48dabdb52d5de50b8048e74) and then this repo was updated in [this commit](https://github.com/PokeAPI/pokeapi/commit/46134774fc4e2f061472b317cabda1bddc0ddb85#diff-1d10c8ae6d04e5f3f00c5eb3f886a7d7930c3f4d0e63456642dfa5a24fe78abf).

**Comment by Naramsim** [comment]
Thanks for the blame @C-Garza :smile: haha

If it's data coming directly from veekun I'd leave it here as well. 

I just checked and the lines are still present. So we keep them.

**Comment by magical** [comment]
Huhh. Interesting. Are the other two forms identical? I wouldn't be opposed to getting rid of them. I feel like we've done that in the past. Similarly with Scatterbug and Spewpa.

**Comment by Naramsim** [comment]
Hi Magical :) Good to see you :)

If you delete them, then we will do the same :) Just do it before merging that huge PR I'm seeing these days :smile:. That will be a pain here at PokeAPI

**Comment by magical** [comment]
Ha, well, if we do delete them it'll be after veekun/pokedex#327 is merged. (I don't want to create a bunch of unnecessary merge conflicts! 😅)

**Comment by 0tobi** [comment]
Burmy still don't have the forms in the ["varieties"](https://pokeapi.co/api/v2/pokemon-species/412)

**Comment by Naramsim** [comment]
We merged the data from Veekun. I don't know if the issue got resolved though.

**Comment by 0tobi** [comment]
> We merged the data from Veekun. I don't know if the issue got resolved though.

Hello, so burmy's forms are in the route https://pokeapi.co/api/v2/pokemon/412 (forms) but wormadam's forms are in the route https://pokeapi.co/api/v2/pokemon-species/413/ (varieties)

and in my projet I use the route of "pokemon-species" (varieties) to get all the Pokémon forms

**Comment by JadeJuno** [comment]
Why was this closed? The issue still persists
https://pokeapi.co/api/v2/pokemon/414/ The `forms` key still has `mothim-plant`, `mothim-sandy` and `mothim-trash` listed as forms, and those forms do exist in the `pokemon-forms` section, when only `mothim-plant` should exist and be renamed to just `mothim`.
